// this file just define for Decoding Log file

#define LOG_CODE_MEANING_CC  "Connecting¡K"                               
#define LOG_CODE_MEANING_CF  "Connection failed."                        
#define LOG_CODE_MEANING_CK  "Connection Okay."                           
#define LOG_CODE_MEANING_DC  "Disconnect."                                
#define LOG_CODE_MEANING_IK  "Successfully get spa information."            
#define LOG_CODE_MEANING_TT  "Go to Data/Time setting."                    
#define LOG_CODE_MEANING_T2  "Set Date/Time as:"                          
#define LOG_CODE_MEANING_TK  "Change Date/Time successfully."                
#define LOG_CODE_MEANING_EE  "Go to ECO mode schedulesetting."
#define LOG_CODE_MEANING_E2  "Set ECO mode schedule as:"      
#define LOG_CODE_MEANING_EK  "Successfully change ECO mode schedule."      
#define LOG_CODE_MEANING_FF  "Go to STD mode filter schedule setting."
#define LOG_CODE_MEANING_F2  "Set STD mode filter schedule as:"     
#define LOG_CODE_MEANING_FK  "Successfully change filter schedule."          
#define LOG_CODE_MEANING_ST  "Set temperature as:"                        
#define LOG_CODE_MEANING_FD  "Set Filter days as:"                        
#define LOG_CODE_MEANING_UD  "Set UV days as:"                            
#define LOG_CODE_MEANING_1H  "Set pump-1 high on."                         
#define LOG_CODE_MEANING_1L  "Set pump-1 low on."                          
#define LOG_CODE_MEANING_1F  "Set pump-1 off."                             
#define LOG_CODE_MEANING_2H  "Set pump-2 high on."                         
#define LOG_CODE_MEANING_2L  "Set pump-2 low on."                          
#define LOG_CODE_MEANING_2F  "Set pump-2 off."                             
#define LOG_CODE_MEANING_3H  "Set pump-3 high on."                         
#define LOG_CODE_MEANING_3L  "Set pump-3 low on."                          
#define LOG_CODE_MEANING_3F  "Set pump-3 off."                             
#define LOG_CODE_MEANING_B1  "Set blower on."                              
#define LOG_CODE_MEANING_B0  "Set blower off."                             
#define LOG_CODE_MEANING_UL  "Set to un-lock."                             
#define LOG_CODE_MEANING_LT  "Set to temperature lock."                    
#define LOG_CODE_MEANING_LS  "Set to service lock."                        
#define LOG_CODE_MEANING_LP  "Set to pump lock."                           
#define LOG_CODE_MEANING_LA  "Set to panel lock."                          
#define LOG_CODE_MEANING_E1  "Set ECO mode on."                            
#define LOG_CODE_MEANING_E0  "Set ECO mode off."                           
#define LOG_CODE_MEANING_EH  "Read and check Error Message history."       
#define LOG_CODE_MEANING_AD  "Auto-diagnostic starts."                   
#define LOG_CODE_MEANING_AK  "Auto-diagnostic completed."                   
#define LOG_CODE_MEANING_HR  "Get history of RDS reports."                 
#define LOG_CODE_MEANING_HL  "Get history of operation records."            
#define LOG_CODE_MEANING_SC  "Service call submitted."                     
#define LOG_CODE_MEANING_SL  "List operator's Open Service Call list."     
#define LOG_CODE_MEANING_RS  "Save RDS Report."                            
#define LOG_CODE_MEANING_RT  "See RDS report."                             
#define LOG_CODE_MEANING_RP  "Print RDS report." 
#define LOG_CODE_MEANING_AN  "Cannot run Auto-Diagnostic due to error ="
#define LOG_CODE_MEANING_AA  "Can run Auto-Diagnostic again."
#define LOG_CODE_MEANING_AF  "Auto-diagnostic saves STD filter schedule as:"
#define LOG_CODE_MEANING_SS  "Go to SF filter schedule setting."
#define LOG_CODE_MEANING_S2  "Set SF."
#define LOG_CODE_MEANING_SK  "Change SF filter schedule sucessfully."
#define LOG_CODE_MEANING_PP  "Go to PF filter schedule setting."
#define LOG_CODE_MEANING_P2  "Set PF as:"
#define LOG_CODE_MEANING_PK  "Change PF filter schedule sucessfully."
#define LOG_CODE_MEANING_XX  "RDS Program exits."
